# Generated by Django 4.1.7 on 2023-03-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_product_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='about',
            new_name='model',
        ),
        migrations.AddField(
            model_name='product',
            name='asset',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sno',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
